### PR TITLE
Add more Chinese TTS models (Mandarin and Cantonese)

### PR DESCRIPTION
**Pull request by csukuangfj**
https://github.com/k2-fsa/sherpa-onnx/tree/tts-models

Screenshot 2024-02-20 at 12 56 25

You can find pre-built Android APKs at
https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html

# Chinese (Mandarin)

Screenshot 2024-02-20 at 15 03 03

# Chinese (Cantonese)
Screenshot 2024-02-20 at 15 03 27

### CODE REVIEW

**Comment by ctop007** [comment]
Hello, we tested and found that the Cantonese model always produces a strange ending sound. We also confirmed this issue using [https://huggingface.co/spaces/k2-fsa/text-to-speech](https://huggingface.co/spaces/k2-fsa/text-to-speech?utm_source=chatgpt.com)
. Could you please let us know if there’s any way to fix this?
Reproduction steps: Select Cantonese, input “今日你哋去食咩？”, and you can hear a noticeable tail sound at the end.

iShot_2025-09-04_11 58 21

**Comment by csukuangfj** [comment]
> 今日你哋去食咩？

Thanks for reporting! We will fix it.

**Comment by csukuangfj** [comment]
@ctop007 

Fixed.

Please build from the latest master or re-try with our huggingface space.

**Comment by ctop007** [comment]
Thank you very much — we have verified that the Cantonese TTS tail sound issue has significantly improved.
In addition, we tested other TTS language models and found that the Greek model also produces a strange sound.

Reproduction steps: Select Greek, input “τι κάνεις”.

**Comment by csukuangfj** [comment]
> Reproduction steps: Select Greek, input “τι κάνεις”.

Please specify which mode you are using. It would be great if you also post a screenshot.

**Comment by ctop007** [comment]
> > 复制步骤：选择希腊语，输入“τι κάνεις”。
> 
> 请具体说明您使用的模式。如果您能上传一下截图就更好了。
iShot_2025-09-04_16 54 43

**Pull request merged**
