### PR TITLE
updated the icon on TTS engine for android

### PR DESCRIPTION
**Pull request by paolo-caroni**
As promised [here](https://github.com/k2-fsa/sherpa-onnx/issues/520) at @csukuangfj I have updated the icon logo.

WARNING: to create the xml files I have vectorized the bitmap image provided with the pdf, especially for foreground start from a vectorial image would lead to less space, since that it should be done to the original author or he/she will send me the official .svg.

Since the space problem I have updated only SherpaOnnxTtsEngine icons, not the other on this repo, that I think would be updated too.

About the fastlane directory I will wait untill #569 is resolved.

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thanks!

Could you post a screenshot about the app after applying this pull request?

**Comment by paolo-caroni** [comment]
Honestly I have not yet compiled it, it's only an image change, not a code change, you can see the webp image raw directly on the repo, for example here:
https://raw.githubusercontent.com/paolo-caroni/sherpa-onnx/master/android/SherpaOnnxTtsEngine/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp

If you want in the next days I will compile it (for the first time, but I have seen that is well documented) and then post here a screenshot :)

**Comment by paolo-caroni** [comment]
Ok, I have corrected it, the problem was that the resolution was too high, too much vectorial points, on android studio I see the previews but on compiling give an error (string too large), sorry.
Here you have the screenshots. I have removed much details from the logo, I would be happy to redone all with the support of the original desiner.
IMG_20240213_194151_968
IMG_20240213_194152_153
IMG_20240213_194152_104
IMG_20240213_194151_647

**Comment by paolo-caroni** [comment]
@csukuangfj I'm really sorry that I assumed everything would work just by looking at the preview. I'm sure that you have noticed it and asked me a screenshot because of this.

**Comment by csukuangfj** [comment]
Great! 

Thank you for your contribution!

**Pull request merged**
