### PR TITLE
Support DirectML for windows

### PR DESCRIPTION
**Pull request by csukuangfj**
Note:  It does not seem to improve the speed when passing `--provider=directml` from the commandline.

### CODE REVIEW

**Comment by thewh1teagle** [comment]
> Note: It does not seem to improve the speed when passing `--provider=directml` from the commandline.

What's something heavy I can test this on? I wanted to test on whisper medium but this branch does not have it.
Can I use sherpa-onnx.exe binary to test something?

**Comment by csukuangfj** [comment]
I think we should resolve the conflict and merge this PR.

If I recall correctly, it has not been merged because it does not run faster with DirectlML.

**Comment by thewh1teagle** [comment]
> it has not been merged because it does not run faster with DirectlML.

I would like to check it and compare

**Comment by thewh1teagle** [comment]
> If I recall correctly, it has not been merged because it does not run faster with DirectlML.

I tried on another c++ project that uses DirectML. it used 95% from the TPU (amd ryzen 5 4500u) 
But it wasn't fast. Maybe it does works slow.
The fastest way to use whisper I found is [CTranslate2](https://github.com/OpenNMT/CTranslate2) and even on CPU only!
Do you have idea how can we get similar results with sherpa?

**Comment by thewh1teagle** [comment]
Any chance you could resolve the conflicts so I can test it with Whisper medium?

**Comment by csukuangfj** [comment]
Closing via #1153

**Pull request closed without merging**
