### PR TITLE
Fix passing C# string to C++

### LINKED ISSUE #835: Generating speach in Russian with C# returns nonsence
Hello and thank you so much for this great repo!

Unfortunately, I came across a very strange bug. When using the standalone application "sherpa-onnx-non-streaming-tts-x64-v1.9.23.exe" from the release -- everything is ok. 
But as soon as I try to generate with the same model, token file and espeak-ng-data using C# -- the output is gibberish (sounds like when you try to feed non-English language to English TTS model). No errors or debug messages. File is successfully generated, but output speech sounds nonsensical.
This bug is reproducible even in the provided example project "dotnet-examples/offline-tts".

### PR DESCRIPTION
**Pull request by csukuangfj**
Fixes #835  

CC @Onkitova

Please use nuget package v1.10.2

### CODE REVIEW

**Comment by Onkitova** [comment]
Wow, thank you!

**Comment by csukuangfj** [comment]
> Wow, thank you!

Does it work for you now?

@Onkitova

**Comment by Onkitova** [comment]
> > Wow, thank you!
> 
> Does it work for you now?
> 
> @Onkitova

Hope so! Going to check it surely in a few hours from now and then I will report back to you.

**Comment by Onkitova** [comment]
@csukuangfj 
Can confirm everything works like charm now! 
Once again, thank you superverymuch for putting effort and attention into solving this! 👍

**Pull request merged**
