### PR TITLE
Text-to-speech for iOS

### PR DESCRIPTION
**Pull request by csukuangfj**
You can find a YouTube video showing how to use it at the following address

https://www.youtube.com/watch?v=MvePdkuMNJk

### CODE REVIEW

**Comment by Web3Kev** [comment]
hello. Thanks for your work. Has the iOS tts branch been moved ? or is it simply not available anymore ?

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/tree/master/ios-swiftui/SherpaOnnxTts

**Comment by Web3Kev** [comment]
Thank you for the link and thanks for this awesome repo ! 
I have successfully built and run iOS-swift/SherpaOnnx but iOS-swiftui/SherpaOnnxTts builds but tts engine always ends up null ... 
Also is it possible to use speech recognition with whisper in iOS-swift/SherpaOnnx? or is it a totally different logic?

**Comment by csukuangfj** [comment]
> always ends up null ...

The information you provided is too limited. Would you mind sharing the complete logs? Otherwise, we are not clear what bad things happened.

---

> Also is it possible to use speech recognition with whisper in iOS-swift/SherpaOnnx?

It is 100% possible. Please see our example
https://github.com/k2-fsa/sherpa-onnx/tree/master/ios-swiftui/SherpaOnnx2Pass

**Comment by Web3Kev** [comment]
thanks for the answer. I get this error :
-[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.
/sherpa-onnx/sherpa-onnx/csrc/offline-tts-vits-model-config.cc:Validate:55 '/private/var/containers/Bundle/Application/61C0135C-7096-41AA-9F5A-4E2D204F5A94/SherpaOnnxTts.app/espeak-ng-data/phontab' does not exist. Skipping test
/sherpa-onnx/sherpa-onnx/c-api/c-api.cc:SherpaOnnxCreateOfflineTts:853 Errors in config
TTS object is null
Failed to generate audio

**Comment by Web3Kev** [comment]
I include the .onnx model along with its espeak-ng-data folder (containing phontab) and tokens.txt. 
I tried with different models  but to no avail.

**Comment by csukuangfj** [comment]
Please describe in detail how you "include" them.

**Comment by Web3Kev** [comment]
I add them to the project, like you describe in the YouTube video.

**Comment by Web3Kev** [comment]
I managed to make it work. The folder was badly imported :  create group vs create folder reference.
I had to fix few issues in the swift-ui code to make it work. Now it works like a charm. 
I am now trying to export all the files : SherpaOnnx.swift and ViewModel.swift in my flutter Xcode workspace in order to call the methods from flutter. 
I have to say that I am not too familiar with Xcode but despite having tried adding onnxruntime.xcframework and sherpa-onnx.xcframework  both copied or simply referred, Xcode cannot find the c-api.h methods declared in SherpaOnnx.swift.
I am very sorry for that noob question but am I missing something ?  Thanks in advance.

**Comment by csukuangfj** [comment]
Glad to hear that you finally managed to make it work.

**Pull request merged**
