### PR TITLE
WIP: Begin to add C# APIs for online ASR

### PR DESCRIPTION
**Pull request by csukuangfj**
Tested with the following file (call it `a.cs`)
```bash
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
cmake --build . --target sherpa-onnx-c-api --config Release
cd bin/release
# You can find the generated DLLs in this folder

# copy a.cs to this folder
csc ./a.cs
./a.exe
```

```c#
using System.Runtime.InteropServices;
using System;

namespace SherpaOnnx {

[StructLayout(LayoutKind.Sequential)]
public struct OnlineTransducerModelConfig {
  [MarshalAs( UnmanagedType.LPStr)]
  public string Encoder;

  [MarshalAs( UnmanagedType.LPStr)]
  public string Decoder;

  [MarshalAs( UnmanagedType.LPStr)]
  public string Joiner;

  [MarshalAs( UnmanagedType.LPStr)]
  public string Tokens;

  public int NumThreads;
  public int Debug;
}

[StructLayout(LayoutKind.Sequential)]
public struct FeatureConfig {
  public int SampleRate;
  public int FeatureDim;
}

[StructLayout(LayoutKind.Sequential)]
public struct OnlineRecognizerConfig {
  public FeatureConfig FeatConfig;
  public OnlineTransducerModelConfig ModelConfig;

  [MarshalAs( UnmanagedType.LPStr)]
  public string DecodingMethod;

  public int MaxActivePaths;
  public int EnableEndpoint;
  public float Rule1MinTrailingSilence;
  public float Rule2MinTrailingSilence;
  public float Rule3MinUtteranceLength;
}


class Online {
  private const string DllName = "sherpa-onnx-c-api.dll";

  [DllImport(DllName)]
  public static extern IntPtr CreateOnlineRecognizer(ref OnlineRecognizerConfig config);
}

class Hello {
  public static void Main(string[] args) {
    OnlineRecognizerConfig config = new OnlineRecognizerConfig();
    config.FeatConfig.SampleRate = 300;
    config.FeatConfig.FeatureDim = 88;

    config.ModelConfig.Encoder = "encoder.pt";
    config.ModelConfig.Decoder = "decoder.pt";
    config.ModelConfig.Joiner = "joiner.pt";
    config.ModelConfig.Tokens = "tokens.pt";
    config.ModelConfig.NumThreads = 20;
    config.ModelConfig.Debug = 10;

    config.DecodingMethod = "greedy_search";
    config.MaxActivePaths = 11;
    config.EnableEndpoint = 22;
    config.Rule1MinTrailingSilence = 1.2F;
    config.Rule2MinTrailingSilence = 1.3F;
    config.Rule2MinTrailingSilence = 1.4F;

    IntPtr ptr = Online.CreateOnlineRecognizer(ref config);
    Console.WriteLine("Hello world");
  }
}

}
```

### CODE REVIEW

**Comment by csukuangfj** [comment]
@manyeyes Please have a look at this PR. I won't merge it. 

You can refactor your code using this PR as a reference.

**Comment by manyeyes** [comment]
> 

okay.

**Comment by manyeyes** [comment]
> @manyeyes Please have a look at this PR. I won't merge it.
> 
> You can refactor your code using this PR as a reference.

okay.

**Comment by csukuangfj** [comment]
By the way, I am building a Nuget package for sherpa-ncnn.

Once I figure out the method, it can also be used for sherpa-onnx as well.

**Pull request closed without merging**
