### PR TITLE
feat: add checksum action

### PR DESCRIPTION
**Pull request by thewh1teagle**
Resolve https://github.com/k2-fsa/sherpa-onnx/issues/1542 using [marketplace/actions/checksums-action](https://github.com/marketplace/actions/checksums-action)

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thank you for your contribution!

**Comment by csukuangfj** [comment]
By the way, could you make it less verbose?

Please see
https://github.com/k2-fsa/sherpa-onnx/actions/runs/12427133835/job/34696468405#step:2:270

```
13950K .......... .......... .......... .......... .......... 91% 99.4M 0s
 14000K .......... .......... .......... .......... .......... 91% 77.1M 0s
 14050K .......... .......... .......... .......... .......... 92%  133M 0s
 14100K .......... .......... .......... .......... .......... 92% 87.3M 0s
 14150K .......... .......... .......... .......... .......... 92%  106M 0s
 14200K .......... .......... .......... .......... .......... 93% 94.1M 0s
 14250K .......... .......... .......... .......... .......... 93% 85.8M 0s
 14300K .......... .......... .......... .......... .......... 93%  140M 0s
 14350K .......... .......... .......... .......... .......... 94% 73.1M 0s
 14400K .......... .......... .......... .......... .......... 94% 93.0M 0s
 14450K .......... .......... .......... .......... .......... 94% 76.8M 0s
 14500K .......... .......... .......... .......... .......... 95%  102M 0s
 14[550](https://github.com/k2-fsa/sherpa-onnx/actions/runs/12427133835/job/34696468405#step:2:553)K .......... .......... .......... .......... .......... 95%  113M 0s
 14600K .......... .......... .......... .......... .......... 95% 80.3M 0s
 14650K .......... .......... .......... .......... .......... 96%  127M 0s
 14700K .......... .......... .......... .......... .......... 96% 90.4M 0s
 14750K .......... .......... .......... .......... .......... 96%  128M 0s
 14800K .......... .......... .......... .......... .......... 97% 81.5M 0s
 14850K .......... .......... .......... .......... .......... 97%  167M 0s
 14900K .......... .......... .......... .......... .......... 97%  104M 0s
 14950K .......... .......... .......... .......... .......... 98%  212M 0s
 15000K .......... .......... .......... .......... .......... 98%  202M 0s
 15050K .......... .......... .......... .......... .......... 98%  154M 0s
 15100K .......... .......... .......... .......... .......... 99%  319M 0s
 15150K .......... .......... .......... .......... .......... 99%  256M 0s
 15200K .......... .......... .......... .......... .......... 99%  249M 0s
 15250K .......... .......... .......... .......... .......... 99%  351M 0s
 15300K                                                       100% 11.8K=0.2s

2024-12-20 07:08:27 (65.5 MB/s) - ‘sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01-mobile.tar.bz2’ saved [1[566](https://github.com/k2-fsa/sherpa-onnx/actions/runs/12427133835/job/34696468405#step:2:569)7804/15667804]
```

**Comment by thewh1teagle** [comment]
> Please see
> https://github.com/k2-fsa/sherpa-onnx/actions/runs/12427133835/job/34696468405

Looks good




> By the way, could you make it less verbose?
> 
> Please see https://github.com/k2-fsa/sherpa-onnx/actions/runs/12427133835/job/34696468405#step:2:270

Fixed and released in https://github.com/thewh1teagle/checksum/commit/5ebda83148e3e0e3fbda9407e2eb3f1dd3b762b0

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
