### PR TITLE
Begin to support CTC models

### PR DESCRIPTION
**Pull request by csukuangfj**
First, we will use CTC models from Nemo for testing.

## TODOs
- [x] CTC greedy search
- [ ] CTC prefix beam search
- [ ] CTC HLG decoding

### CODE REVIEW

**Comment by csukuangfj** [comment]
cc @titu1994 @uni-manjunath-ke
You may find this PR also interesting in addition to the one in https://github.com/k2-fsa/sherpa/pull/332

# Usage of this PR

## Build sherpa-onnx
```bash
cd /tmp/
git clone https://github.com/k2-fsa/sherpa-onnx
cd sherpa-onnx
mkdir build
cd build
cmake -DSHERPA_ONNX_ENABLE_PYTHON=ON -DBUILD_SHARED_LIBS=ON ..
make -j 
export PYTHONPATH=$PWD/lib:$PWD/../sherpa-onnx/python:$PYTHONPATH
```

## Download pre-trained models
```bash
cd /tmp/sherpa-onnx
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/sherpa-onnx-nemo-ctc-en-citrinet-512
cd sherpa-onnx-nemo-ctc-en-citrinet-512
git lfs pull --include "*.onnx"
```

Please refer to
https://huggingface.co/csukuangfj/sherpa-onnx-nemo-ctc-en-citrinet-512/tree/main
for how the model is exported and quantized.

## Use pre-compiled binary from C++ code
```bash
cd /tmp/sherpa-onnx

./build/bin/sherpa-onnx-offline \
  --tokens=./sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt \
  --nemo-ctc-model=./sherpa-onnx-nemo-ctc-en-citrinet-512/model.onnx \
  --num-threads=2 \
  --decoding-method=greedy_search \
  --debug=false \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
```

**Note**: Please replace `model.onnx` with `model.int8.onnx` to use int8 quantized model.

Its output is given below:
```
OfflineRecognizerConfig(feat_config=OfflineFeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OfflineModelConfig(transducer=OfflineTransducerModelConfig(encoder_filename="", decoder_filename="", joiner_filename=""), paraformer=OfflineParaformerModelConfig(model=""), nemo_ctc=OfflineNemoEncDecCtcModelConfig(model="./sherpa-onnx-nemo-ctc-en-citrinet-512/model.onnx"), tokens="./sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt", num_threads=2, debug=False), decoding_method="greedy_search")
Creating recognizer ...
Started
/Users/fangjun/open-source/sherpa-onnx/sherpa-onnx/csrc/offline-stream.cc:AcceptWaveformImpl:105 Creating a resampler:
   in_sample_rate: 8000
   output_sample_rate: 16000

Done!

./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav
 after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
----
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav
 god as a direct consequence of the sin which man thus punished had given her a lovely child whose place was on that same dishonoured bosom to connect her parent for ever with the race and descent of mortals and to be finally a blessed soul in heaven
----
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
 yet these thoughts affected hester prynne less with hope than apprehension
----
num threads: 2
decoding method: greedy_search
Elapsed seconds: 5.080 s
Real time factor (RTF): 5.080 / 28.165 = 0.180
```

## Use Python APIs
```bash
cd /tmp/sherpa-onnx

python3 ./python-api-examples/offline-decode-files.py \
  --tokens=./sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt \
  --nemo-ctc=./sherpa-onnx-nemo-ctc-en-citrinet-512/model.onnx \
  --num-threads=2 \
  --decoding-method=greedy_search \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav \
  ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
```

The output is given below:
```
/Users/fangjun/open-source/sherpa-onnx/sherpa-onnx/csrc/offline-stream.cc:AcceptWaveformImpl:105 Creating a resampler:
   in_sample_rate: 8000
   output_sample_rate: 16000

Done!
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav
 after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
----------
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav
 god as a direct consequence of the sin which man thus punished had given her a lovely child whose place was on that same dishonoured bosom to connect her parent for ever with the race and descent of mortals and to be finally a blessed soul in heaven
----------
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
 yet these thoughts affected hester prynne less with hope than apprehension
----------
num_threads: 2
decoding_method: greedy_search
Wave duration: 28.165 s
Elapsed time: 3.472 s
Real time factor (RTF): 3.472/28.165 = 0.123
```

## Start WebSocket Server (written in C++)
```bash
./build/bin/sherpa-onnx-offline-websocket-server \
  --port=6006 \
  --num-work-threads=5 \
  --num-io-threads=2 \
  --max-batch-size=5 \
  --tokens=./sherpa-onnx-nemo-ctc-en-citrinet-512/tokens.txt \
  --nemo-ctc-model=./sherpa-onnx-nemo-ctc-en-citrinet-512/model.onnx \
  --decoding-method=greedy_search \
  --debug=false
```

## Start WebSocket client (written in Python)
```bash
python3 ./python-api-examples/offline-websocket-client-decode-files-paralell.py \
  --server-addr localhost \
  --server-port 6006 \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
```

The output is given below:
```
2023-04-07 17:09:51,252 INFO [offline-websocket-client-decode-files-paralell.py:133] {'server_addr': 'localhost', 'server_port': 6006, 'sound_files': ['./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav', './sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav', './sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav']}
2023-04-07 17:09:51,280 INFO [offline-websocket-client-decode-files-paralell.py:113] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav
2023-04-07 17:09:51,282 INFO [offline-websocket-client-decode-files-paralell.py:113] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav
2023-04-07 17:09:51,287 INFO [offline-websocket-client-decode-files-paralell.py:113] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
2023-04-07 17:09:52,012 INFO [offline-websocket-client-decode-files-paralell.py:125] ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
 yet these thoughts affected hester prynne less with hope than apprehension
2023-04-07 17:09:52,205 INFO [offline-websocket-client-decode-files-paralell.py:125] ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav
 after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
2023-04-07 17:09:53,000 INFO [offline-websocket-client-decode-files-paralell.py:125] ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav
 god as a direct consequence of the sin which man thus punished had given her a lovely child whose place was on that same dishonoured bosom to connect her parent for ever with the race and descent of mortals and to be finally a blessed soul in heaven
```

## Start WebSocket client 2(written in Python)
```bash
python3 ./python-api-examples/offline-websocket-client-decode-files-sequential.py \
--server-addr localhost \
--server-port 6006 \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav \
./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
```

The output is given below:
```
2023-04-07 17:13:36,388 INFO [offline-websocket-client-decode-files-sequential.py:134] {'server_addr': 'localhost', 'server_port': 6006, 'sound_files': ['./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav', './sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav', './sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav']}
2023-04-07 17:13:36,417 INFO [offline-websocket-client-decode-files-sequential.py:114] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/0.wav
 after early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels
2023-04-07 17:13:37,018 INFO [offline-websocket-client-decode-files-sequential.py:114] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/1.wav
 god as a direct consequence of the sin which man thus punished had given her a lovely child whose place was on that same dishonoured bosom to connect her parent for ever with the race and descent of mortals and to be finally a blessed soul in heaven
2023-04-07 17:13:38,394 INFO [offline-websocket-client-decode-files-sequential.py:114] Sending ./sherpa-onnx-nemo-ctc-en-citrinet-512/test_wavs/8k.wav
 yet these thoughts affected hester prynne less with hope than apprehension
```

**Comment by titu1994** [comment]
Are these on CPU? 0.12 RTF for Citrinet is good, I wonder if Conformers will be fast enough for inference.

**Comment by csukuangfj** [comment]
> Are these on CPU? 0.12 RTF for Citrinet is good, I wonder if Conformers will be fast enough for inference.

Yes, it is on CPU. I will try conformer ctc and post the results here.

**Comment by csukuangfj** [comment]
@titu1994 
Please refer to
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-ctc/nemo/english.html
about the RTF for Conformer CTC.

It is 0.042 for `stt_en_conformer_ctc_medium`, while it is `0.126` for `stt_en_conformer_ctc_large`.

**Comment by titu1994** [comment]
It's 3x faster than Citrinet medium? Surprising. And conformer large is about as efficient as Citrinet medium. Seems quite odd but I suppose for small audio segments attention is faster than convolution.

**Pull request merged**
