### PR TITLE
For java ci actions

### PR DESCRIPTION
**Pull request by zhaomingwork**
Not very familiar with this field, just refer to jni.yaml and make some changes. pls help check.

### CODE REVIEW

**Comment by csukuangfj** [comment]
The error logs are available at
https://github.com/k2-fsa/sherpa-onnx/actions/runs/5733672974/job/15538712032

From the error logs:
```
/home/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/jni/jni.cc:Java_com_k2fsa_sherpa_onnx_OnlineRecognizer_createOnlineRecognizer:415 config:
OnlineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OnlineTransducerModelConfig(encoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx", decoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/decoder-epoch-99-avg-1.onnx", 

....

terminate called after throwing an instance of 'Ort::Exception'
  what():  No graph was found in the protobuf.
make: *** [Makefile:69: runfile] Aborted (core dumped)

```

> encoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx"

So it seems to me that this path does not exist.

**Comment by zhaomingwork** [comment]
> The error logs are available at https://github.com/k2-fsa/sherpa-onnx/actions/runs/5733672974/job/15538712032
> 
> From the error logs:
> 
> ```
> /home/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/jni/jni.cc:Java_com_k2fsa_sherpa_onnx_OnlineRecognizer_createOnlineRecognizer:415 config:
> OnlineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OnlineTransducerModelConfig(encoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx", decoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/decoder-epoch-99-avg-1.onnx", 
> 
> ....
> 
> terminate called after throwing an instance of 'Ort::Exception'
>   what():  No graph was found in the protobuf.
> make: *** [Makefile:69: runfile] Aborted (core dumped)
> ```
> 
> > encoder_filename="/sherpa/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx"
> 
> So it seems to me that this path does not exist.

my mistake. pull a new commit.

**Comment by csukuangfj** [comment]
It fails for macOS
https://github.com/k2-fsa/sherpa-onnx/actions/runs/5758801397/job/15611867921?pr=231

```
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/jni/jni.cc:12:10: fatal error: 'jni.h' file not found
#include "jni.h"  // NOLINT
         ^~~~~~~
1 error generated.
```

I suggest that we test only Linux first and remove the test for macOS from github actions for now.

**Comment by zhaomingwork** [comment]
> It fails for macOS https://github.com/k2-fsa/sherpa-onnx/actions/runs/5758801397/job/15611867921?pr=231
> 
> ```
> /Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/jni/jni.cc:12:10: fatal error: 'jni.h' file not found
> #include "jni.h"  // NOLINT
>          ^~~~~~~
> 1 error generated.
> ```
> 
> I suggest that we test only Linux first and remove the test for macOS from github actions for now.

Sure. committed new one.

**Comment by csukuangfj** [comment]
Thanks!

**Pull request merged**
