### PR TITLE
fix garbled console output with chinese characters

### PR DESCRIPTION
**Pull request by dongqianzhuan**
chinese characters can normal show in console

### CODE REVIEW

**Comment by csukuangfj** [comment]
Thanks!

**Comment by danpovey** [comment]
what is the point of the sherpa_onnx.Display ?  He seems to be using normal printing instead?

**Comment by dongqianzhuan** [comment]
> what is the point of the sherpa_onnx.Display ? He seems to be using normal printing instead?
i think it is fprintf bug,in the different format console ,may be have some problem.like chineses in winows cmd console

**Comment by csukuangfj** [comment]
> He seems to be using normal printing instead?

The key to his usage of printing is `end=""` and `\r`, though it cannot handle the case when a sentence expands multiple lines.

> what is the point of the sherpa_onnx.Display ? 

`sherpa_onnx.Display()` clears the previously displayed results from the terminal. To give you a concrete example,
when the recognition result is `what day is today`, instead of displaying it in the following form
```
what
what day
what day is
what day is today
```
`sherpa_onnx.Display()` displays the whole sentence in a single line.

**Comment by csukuangfj** [comment]
The issue is that on **some** (not all) windows systems, `sherpa_onnx.Display()` cannot handle the encoding correctly, while python's `print` works fine.

**Pull request merged**
